import 'package:todo_app/models/task.dart';

final List<Task> tasks = [
  Task(
    id: '1',
    title: 'Faire les courses',
    description: 'Acheter du pain, du lait, des fruits et légumes.',
    author: 'John Doe',
    createdAt: DateTime(2023, 10, 11, 07, 36, 56),
    isCompleted: false,
  ),
  Task(
    id: '2',
    title: 'Apprendre le français',
    description: 'Faire une leçon sur Duolingo et lire un article en français.',
    author: 'Jane Doe',
    createdAt: DateTime(2023, 10, 11, 07, 36, 56),
    isCompleted: true,
  ),
  Task(
    id: '3',
    title: 'Ranger la maison',
    description: 'Dépoussiérer, passer l\'aspirateur et faire la vaisselle.',
    author: 'John Doe',
    createdAt: DateTime(2023, 10, 11, 07, 36, 56),
    isCompleted: false,
  ),
  Task(
    id: '4',
    title: 'Préparer le dîner',
    description: 'Cuisiner un plat simple et équilibré.',
    author: 'Jane Doe',
    createdAt: DateTime(2023, 10, 11, 07, 36, 56),
    isCompleted: false,
  ),
  Task(
    id: '5',
    title: 'Répondre aux emails',
    description: 'Répondre aux emails urgents et importants.',
    author: 'John Doe',
    createdAt: DateTime(2023, 10, 11, 07, 36, 56),
    isCompleted: true,
  ),
  Task(
    id: '6',
    title: 'Appeler le médecin',
    description: 'Prendre rendez-vous pour un bilan de santé.',
    author: 'Jane Doe',
    createdAt: DateTime(2023, 10, 11, 07, 36, 56),
    isCompleted: false,
  ),
  Task(
    id: '7',
    title: 'Faire du sport',
    description: 'Aller courir ou faire une séance de yoga.',
    author: 'John Doe',
    createdAt: DateTime(2023, 10, 11, 07, 36, 56),
    isCompleted: true,
  ),
  Task(
    id: '8',
    title: 'Lire un livre',
    description: 'Lire un chapitre de votre livre préféré.',
    author: 'Jane Doe',
    createdAt: DateTime(2023, 10, 11, 07, 36, 56),
    isCompleted: false,
  ),
  Task(
    id: '9',
    title: 'Regarder un film',
    description: 'Choisir un film relaxant et divertissant.',
    author: 'John Doe',
    createdAt: DateTime(2023, 10, 11, 07, 36, 56),
    isCompleted: false,
  ),
  Task(
    id: '10',
    title: 'Passer du temps en famille',
    description: 'Organiser un jeu de société ou une activité amusante.',
    author: 'Jane Doe',
    createdAt: DateTime(2023, 10, 11, 07, 36, 56),
    isCompleted: true,
  ),
];
